/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAffix: typeof import('ant-design-vue/es')['Affix']
    AAlert: typeof import('ant-design-vue/es')['Alert']
    AAnchor: typeof import('ant-design-vue/es')['Anchor']
    AButton: typeof import('ant-design-vue/es')['Button']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElRow: typeof import('element-plus/es')['ElRow']
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    HelloWorlds: typeof import('./../src/components/HelloWorlds/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../src/components/SvgIcon/index.vue')['default']
    VanActionBar: typeof import('vant/es')['ActionBar']
    VanButton: typeof import('vant/es')['Button']
  }
}
